(define (problem logisticproblem1)
  (:domain logisticproblem)
  (:objects truck package1 tampinese changi bedok)
  (:init (truck truck)
    (package package1)    
    (location tampinese)
    (location changi)    
    (location bedok)
    (at-truck truck tampinese)
    (at-package package1 bedok)
    (road tampinese changi)
    (road changi tampinese)
    (road changi bedok)
    (road bedok changi)
    (road tampinese bedok)
    (road bedok tampinese))

  (:goal (and (at-package package1 changi))))